Himanshu Hansaria
8744957457

### Numpy, Pandas, and Prediction


## Name: 

<div class="alert alert-danger" role="alert">
Note: You must print the output of each question in a new cell below your code. Homework submissions without outputs displayed will not be graded.
    </div>

## Numpy Review


__1a) Create two numpy arrays (`a` and `b`).__

* `a` should be all integers between 25-34 (inclusive)
* `b` should be ten evenly spaced numbers between 1-6. 


**Print all the results for 1-4 below and solve them consecutively:**


1. Cube (i.e. raise to the power of 3) all the elements in both arrays (element-wise)  
2. Add the cubed arrays `a^3 + b^3` (e.g., `[1,2] + [3,4] = [4,6]`)  
3. Sum the elements with even indices of the added array from `2.`  
4. Take the square root of the added array (element-wise square root)




In [1]:
import numpy as np

In [11]:
a = np.linspace(25, 34, 10, dtype= int)

In [13]:
b = np.linspace(1, 6, 10)

In [19]:
print(a ** 3)

[15625 17576 19683 21952 24389 27000 29791 32768 35937 39304]


In [20]:
print(b ** 3)

[  1.           3.76406036   9.40877915  18.96296296  33.45541838
  53.91495199  81.37037037 116.85048011 161.38408779 216.        ]


In [18]:
c = a ** 3 + b ** 3
print(c)

[15626.         17579.76406036 19692.40877915 21970.96296296
 24422.45541838 27053.91495199 29872.37037037 32884.85048011
 36098.38408779 39520.        ]


In [17]:
sum = 0
for i in range(len(c)):
    if i != 0 and i % 2 == 0:
        sum += c[i]
print(sum)

110085.61865569273


In [22]:
print(np.sqrt(c))

[125.00399994 132.58870261 140.32964327 148.22605359 156.27685503
 164.48074341 172.83625306 181.34180566 189.99574755 198.79637824]


__1b) Append `b` to `a`, reshape the appended array so that it is a 4x5 2d array. Store the results in a variable called `m`. Print `m`.__

In [28]:
d = np.concatenate((a,b))

In [31]:
m = d.reshape(4,5)

In [32]:
print(m)

[[25.         26.         27.         28.         29.        ]
 [30.         31.         32.         33.         34.        ]
 [ 1.          1.55555556  2.11111111  2.66666667  3.22222222]
 [ 3.77777778  4.33333333  4.88888889  5.44444444  6.        ]]


__1c) Extract the third and the fourth column of the `m` matrix. Store the resulting 4x2 matrix in a new variable called `m2`. Print `m2`.__


In [41]:
m2 = m[:, 2:4]
print(m2)

[[27.         28.        ]
 [32.         33.        ]
 [ 2.11111111  2.66666667]
 [ 4.88888889  5.44444444]]


__1d) Take the dot product of `m2` and `m` store the results in a matrix called `m3`. Print `m3`.
Note that Dot product of two matrices A.B =A<sup>T</sup>B__

In [50]:
m2_T = m2.transpose()
m3 = m2_T.dot(m)
print(m3)

[[1655.58024691 1718.4691358  1781.35802469 1844.24691358 1907.13580247]
 [1713.2345679  1778.74074074 1844.24691358 1909.75308642 1975.25925926]]


## Numpy conditions


__2a) Create a Numpy array called `f` containing the values of `cosine(x)` for x from 0 to $\pi$ in 50 equally spaced value increments__
* 1. Print `f`
* 2. Use condition mask and print an array that is `True` when `f >= 1/2` and `False` when `f < 1/2`
* 3. Create and print an array sequence that has only those values where `f>= 1/2`



In [69]:
x = np.linspace(0, np.pi, 50)
f = np.cos(x)
print(f)
print(f >= 1/2)
arr = f[f>=1/2]
print(arr)

[ 1.          0.99794539  0.99179001  0.98155916  0.96729486  0.94905575
  0.92691676  0.90096887  0.8713187   0.8380881   0.80141362  0.76144596
  0.71834935  0.67230089  0.6234898   0.57211666  0.51839257  0.46253829
  0.40478334  0.34536505  0.28452759  0.22252093  0.1595999   0.09602303
  0.03205158 -0.03205158 -0.09602303 -0.1595999  -0.22252093 -0.28452759
 -0.34536505 -0.40478334 -0.46253829 -0.51839257 -0.57211666 -0.6234898
 -0.67230089 -0.71834935 -0.76144596 -0.80141362 -0.8380881  -0.8713187
 -0.90096887 -0.92691676 -0.94905575 -0.96729486 -0.98155916 -0.99179001
 -0.99794539 -1.        ]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False]
[1.         0.99794539 0.99179001 0.98155916 0.96729486 0.94905575
 0.92691676 0.90096

## NumPy and 2 Variable Prediction

__Let `x` be the number of miles a person drives per day and `y` be the dollars spent on buying car fuel (per day).__
  
We have created 2 numpy arrays each of size 100 that represent `x` and `y`.
* `x` ( number of miles) ranges from 1 to 10 with a uniform noise of (0,1/2)  
* `y` (money spent in dollars) will be from 1 to 20 with a uniform noise (0,1) 


In [122]:
# seed the random number generator with a fixed value
import numpy as np
np.random.seed(500)

x = np.linspace(1,10,100)+ np.random.uniform(low=0,high=.5,size=100) 
y = np.linspace(1,20,100)+ np.random.uniform(low=0,high=1,size=100)
print('x = ',x)
print('y = ',y)

x =  [ 1.34683976  1.12176759  1.51512398  1.55233174  1.40619168  1.65075498
  1.79399331  1.80243817  1.89844195  2.00100023  2.3344038   2.22424872
  2.24914511  2.36268477  2.49808849  2.8212704   2.68452475  2.68229427
  3.09511169  2.95703884  3.09047742  3.2544361   3.41541904  3.40886375
  3.50672677  3.74960644  3.64861355  3.7721462   3.56368566  4.01092701
  4.15630694  4.06088549  4.02517179  4.25169402  4.15897504  4.26835333
  4.32520644  4.48563164  4.78490721  4.84614839  4.96698768  5.18754259
  5.29582013  5.32097781  5.0674106   5.47601124  5.46852704  5.64537452
  5.49642807  5.89755027  5.68548923  5.76276141  5.94613234  6.18135713
  5.96522091  6.0275473   6.54290191  6.4991329   6.74003765  6.81809807
  6.50611821  6.91538752  7.01250925  6.89905417  7.31314433  7.20472297
  7.1043621   7.48199528  7.58957227  7.61744354  7.6991707   7.85436822
  8.03510784  7.80787781  8.22410224  7.99366248  8.40581097  8.28913792
  8.45971515  8.54227144  8.6906456   8.618565

__3a) Find Expected value of `x` and the Expected value of `y`__

In [123]:
# your code here
print(x.mean())
print(y.mean())

5.782532541587923
11.012981683344968


__3b) Find variance of `x` and `y`__

In [126]:
# your code here
print(x.var())
print(y.var())

7.03332752947585
30.113903575509635


__3c) Find covariance of `x` and `y`.__

In [129]:
# your code here
print(np.cov(x,y))

[[ 7.10437124 14.65774383]
 [14.65774383 30.41808442]]


__3d) Assuming that number of dollars spent on car fuel is only dependent on the miles driven, by  a linear relationship.  
Write code that finds the model paramters `c` and `m` for a linear predictor to calculate a predicted value of `y` for each `x`
i.e $\hat{y}$=`y_predicted = f(x) = c+mx`. (Do not use Machine learning libraries, only native Numpy).__

Print `m` and `c`

In [134]:
# your code here
m, c = np.polyfit(x,y, 1)
print(m)
print(c)

2.063200715971324
-0.9175435965867221


__3e) Predict `y` for each value in `x`. Calculate the Squared Error (SE), ie $SE = \sum^{100}_1 (\hat{y}-y)^2$, store the squared errors in an array called `y_error`__

In [141]:
# your code here
y_pred = m * x + c 
y_error = (y - y_pred) ** 2
y_error = y_error.sum()
print(y_error)

17.445468084895097


__3f) Write code that calculates the root mean square error(RMSE), that is the square root of the mean of `y_error`__


In [143]:
# your code here
print(np.sqrt(y_error.mean()))

4.176777236685612


## Pandas Introduction

In order to complete some of these problems you might need to go over the Data-X Pandas notebook (depending on how much Pandas you've used).

You can find the Pandas notebook in the Github repository: [github.com/afo/data-x-plaksha](github.com/afo/data-x-plaksha) (look in the folder `02b-tools-pandas` for the notebook `pandas-intro-v8_short.ipynb`

##  Reading File


In [71]:
# Load required modules
import pandas as pd
import numpy as np



#### Read the CSV file called `'data3.csv'` into a dataframe called `df`. 
#### Data description
* File location: Attached along
* Data source: http://www.fao.org/nr/water/aquastat/data/query/index.html?*lang=en
* Data, units:
* GDP, current USD (CPI adjusted)
* NRI, mm/yr
* Population density, inhab/km^2
* Total area of the country, 1000 ha = 10km^2
* Total Population, unit 1000 inhabitants


In [153]:
df = pd.read_csv('contest.csv', header = 1)

#### 4a ) Display the first 10 rows of the dataframe

In [154]:
df.head(10)

Area  Area Id              Variable Name  Variable Id  Year     Value  \
0  Argentina        9  Total area of the country         4100  1962  278040.0   
1  Argentina        9  Total area of the country         4100  1967  278040.0   
2  Argentina        9  Total area of the country         4100  1972  278040.0   
3  Argentina        9  Total area of the country         4100  1977  278040.0   
4  Argentina        9  Total area of the country         4100  1982  278040.0   
5  Argentina        9  Total area of the country         4100  1987  278040.0   
6  Argentina        9  Total area of the country         4100  1992  278040.0   
7  Argentina        9  Total area of the country         4100  1997  278040.0   
8  Argentina        9  Total area of the country         4100  2002  278040.0   
9  Argentina        9  Total area of the country         4100  2007  278040.0   

  Symbol  
0      E  
1      E  
2      E  
3      E  
4      E  
5      E  
6      E  
7      E  
8      E  
9      E

#### 4b) Display the column names.

In [155]:
for col in df.columns:
    print(col)

Area
Area Id
Variable Name
Variable Id
Year
Value
Symbol


#### 4c) Use iloc to display the first 3 rows and first 4 columns.

In [156]:
df.iloc[:3,:4]

Area  Area Id              Variable Name  Variable Id
0  Argentina        9  Total area of the country         4100
1  Argentina        9  Total area of the country         4100
2  Argentina        9  Total area of the country         4100



## Data Preprocessing

#### 5a ) Find all the rows that  have 'NaN' in the 'Symbol' column. Display the first 5 rows of this result.

##### Hint : You might have to use a condition (mask)

In [157]:
cut = df['Symbol'] == np.nan
df[cut].head(5)

Empty DataFrame
Columns: [Area, Area Id, Variable Name, Variable Id, Year, Value, Symbol]
Index: []

#### 5b )  Now, we will try to get rid of the NaN valued rows and columns. 

1. First, drop the column 'Other' which only has 'NaN' values. 
2. Then drop all other rows that have any column with a value 'NaN'.  
3. Then display the last 5 rows of the dataframe.

In [161]:
# your code here
df.drop('Other', axis = 1, inplace=True)
df.dropna(axis=0).tail(5)

Area  Area Id                  Variable Name  \
385  United States of America      231  National Rainfall Index (NRI)   
386  United States of America      231  National Rainfall Index (NRI)   
387  United States of America      231  National Rainfall Index (NRI)   
388  United States of America      231  National Rainfall Index (NRI)   
389  United States of America      231  National Rainfall Index (NRI)   

     Variable Id  Year   Value Symbol  
385         4472  1981   949.2      E  
386         4472  1984   974.6      E  
387         4472  1992  1020.0      E  
388         4472  1996  1005.0      E  
389         4472  2002   938.7      E




#### 6a) For our analysis we do not want all the columns in our dataframe. Lets  drop all the redundant columns/ features.   
**Drop columns**: **Area Id, Variable Id, Symbol**. Save the new dataframe as `df1`. 


Display the first 5 rows of the new dataframe.


In [164]:
# your code here
df1 = df.drop(['Area Id', 'Variable Id', 'Symbol'], axis = 1)
df1.head()

Area              Variable Name  Year     Value
0  Argentina  Total area of the country  1962  278040.0
1  Argentina  Total area of the country  1967  278040.0
2  Argentina  Total area of the country  1972  278040.0
3  Argentina  Total area of the country  1977  278040.0
4  Argentina  Total area of the country  1982  278040.0

#### 6b) Find all unique values in your new dataframe for columns: 
1. Area
2. Variable Name
3. Year

In [168]:
# your code here
print(pd.unique(df1['Area']))
print(pd.unique(df1['Variable Name']))
print(pd.unique(df1['Year']))

['Argentina' 'Australia' 'Germany' 'Iceland' 'Ireland' 'Sweden'
 'United States of America']
['Total area of the country' 'Total population' 'Population density'
 'Gross Domestic Product (GDP)' 'National Rainfall Index (NRI)']
[1962 1967 1972 1977 1982 1987 1992 1997 2002 2007 2012 2014 2015 1963
 1970 1974 1978 1984 1990 1964 1981 1985 1996 2001 1969 1973 1979 1993
 1971 1975 1986 1991 1998 2000 1965 1983 1988 1995]


#### 6c) Convert the `Year` column to pandas datetime objects 

1. Convert the `Year` column float values to pandas datetime objects, where each year is represented as the first day of that year. Also display the column and datatype for `Year` after conversion.


For eg: `1962.0` will be represented as `1962-01-01`


In [200]:
df1['Year'] = pd.to_datetime(df1['Year'])
df1['Year'].dtype
df1['Year']

0     1970-01-01 00:00:00.000001962
1     1970-01-01 00:00:00.000001967
2     1970-01-01 00:00:00.000001972
3     1970-01-01 00:00:00.000001977
4     1970-01-01 00:00:00.000001982
                   ...             
385   1970-01-01 00:00:00.000001981
386   1970-01-01 00:00:00.000001984
387   1970-01-01 00:00:00.000001992
388   1970-01-01 00:00:00.000001996
389   1970-01-01 00:00:00.000002002
Name: Year, Length: 390, dtype: datetime64[ns]

## Extract specific statistics from the preprocessed data:

#### 7a)  Create a dataframe `dftemp` to store rows where `Area` is `Iceland`.

Display the dataframe `dftemp`.

In [204]:
# your code here
dftemp = df[df['Area'] == 'Iceland']
print(dftemp)

        Area  Area Id                  Variable Name  Variable Id  Year  \
166  Iceland       99      Total area of the country         4100  1962   
167  Iceland       99      Total area of the country         4100  1967   
168  Iceland       99      Total area of the country         4100  1972   
169  Iceland       99      Total area of the country         4100  1977   
170  Iceland       99      Total area of the country         4100  1982   
171  Iceland       99      Total area of the country         4100  1987   
172  Iceland       99      Total area of the country         4100  1992   
173  Iceland       99      Total area of the country         4100  1997   
174  Iceland       99      Total area of the country         4100  2002   
175  Iceland       99      Total area of the country         4100  2007   
176  Iceland       99      Total area of the country         4100  2012   
177  Iceland       99      Total area of the country         4100  2014   
178  Iceland       99    

#### 7b) Print the years when the `National Rainfall Index (NRI)` was greater than 900 and less than 950 in Iceland. 

Use the dataframe you created in the previous question 7a), ie `dftemp`. 

In [205]:
# your code here
dftemp[dftemp['National Rainfall Index (NRI)'] > 900 and dftemp['National Rainfall Index (NRI)'] < 950]

KeyError: 'National Rainfall Index (NRI)'

## US statistics: 


#### 8a) Create a new DataFrame called `df_usa` that only contains values where `Area` is equal to `United States of America`. 

Set the indices of `df_usa` to be the `Year` column with Pandas datetime values ( Use method `.set_index( )` ). Display the head of `df_usa`.

In [317]:
# your code here
df_usa = df[df['Area'] == 'United States of America']
df_usa.set_index('Year')
df_usa.head()
df_temp = df_usa


#### 8b) Pivot the DataFrame `df_usa` so that the unique values in the column `Variable Name` becomes the columns. 

The DataFrame values should be the ones in the the `Value` column. Save it as `df_usa` and display the updated dataframe head.

In [285]:
# your code here
# cols = []
# cols.extend(pd.unique(df_usa['Variable Name']))
df_usa = df_usa.pivot(columns ='Variable Name', values = 'Value')
df_usa.head()

Variable Name  Gross Domestic Product (GDP)  National Rainfall Index (NRI)  \
334                                     NaN                            NaN   
335                                     NaN                            NaN   
336                                     NaN                            NaN   
337                                     NaN                            NaN   
338                                     NaN                            NaN   

Variable Name  Population density  Total area of the country  Total population  
334                           NaN                   962909.0               NaN  
335                           NaN                   962909.0               NaN  
336                           NaN                   962909.0               NaN  
337                           NaN                   962909.0               NaN  
338                           NaN                   962909.0               NaN

#### 8c) Rename the new columns to  `['GDP','NRI','PD','Area','Population']`, display the dataframe head.


In [287]:
# your code here
df_usa.columns = ['GDP','NRI','PD','Area','Population']
df_usa.head()

GDP  NRI  PD      Area  Population
334  NaN  NaN NaN  962909.0         NaN
335  NaN  NaN NaN  962909.0         NaN
336  NaN  NaN NaN  962909.0         NaN
337  NaN  NaN NaN  962909.0         NaN
338  NaN  NaN NaN  962909.0         NaN

#### 8d) Replace all 'Nan' values in `df_usa` with 0. Display the head of the dataframe.

In [299]:
# your code here
df_usa = df_usa.fillna(0)

## Note: Use `df_usa`

#### 9a) Multiply the `'Area'` column for all countries by 10 (so instead of 1000 ha, the unit becomes 100 ha = 1km^2). Display the dataframe head.


In [300]:
# your code here
df_usa['Area'] = df_usa['Area'] * 10
df_usa.head()

GDP  NRI   PD         Area  Population
334  0.0  0.0  0.0  962909000.0         0.0
335  0.0  0.0  0.0  962909000.0         0.0
336  0.0  0.0  0.0  962909000.0         0.0
337  0.0  0.0  0.0  962909000.0         0.0
338  0.0  0.0  0.0  962909000.0         0.0


#### 9b) Create a new column in `df_usa` called `'GDP/capita'` and populate it with the calculated GDP per capita. Round the results to two decimal points. Display the dataframe head.
GDP per capita = (GDP / Population)

In [301]:
# your code here
df_usa['GDP/capita'] = df_usa['GDP'] / df_usa['Population']


#### 9c) Find the maximum value of the `'NRI'` column in the US (using pandas methods). What year does the max value occur? Display the values.

In [319]:
# your code here
df_usa['NRI'].max()
df_temp['Year']

KeyError: 'NRI'