In [1]:
import numpy as np

In [49]:
a = np.array([12, 34, 67])

In [50]:
a.shape # No. of elements along the axis

(3, 1)

In [6]:
a.size # No. of items

3

In [7]:
a.dtype

dtype('int64')

In [8]:
b = np.array([12, 34, 67], dtype = np.int8)

In [9]:
b.dtype

dtype('int8')

In [11]:
c = np.array([[11, 12], [22, 23]])

In [12]:
c

array([[11, 12],
       [22, 23]])

In [13]:
c.shape

(2, 2)

In [14]:
c.size

4

In [17]:
d = np.array([[11, 12], [22, 23, 24]])

In [18]:
d.shape

(2,)

In [19]:
d

array([list([11, 12]), list([22, 23, 24])], dtype=object)

In [21]:
d = np.array([[[[[1]]]], [[[[0]]]]])

In [22]:
d

array([[[[[1]]]],



       [[[[0]]]]])

In [59]:
e = np.array([[[2, 2],[3, 3], [4, 4]], [[4, 4], [5, 5], [6, 6]]])

In [60]:
f = np.array([[[2], [3], [4]],[[4], [5], [6]]] )

In [61]:
e.shape

(2, 3, 2)

In [58]:
f.shape

(2, 3, 1)

In [25]:
np.array(range(100))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [27]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [29]:
first = np.arange(12)

In [30]:
second = first.reshape(4, 3)

In [31]:
third = first.reshape(3, 1, 2, 1, 2)

In [32]:
third

array([[[[[ 0,  1]],

         [[ 2,  3]]]],



       [[[[ 4,  5]],

         [[ 6,  7]]]],



       [[[[ 8,  9]],

         [[10, 11]]]]])

In [33]:
third.ndim

5

In [34]:
first[0] = 1000

In [35]:
second

array([[1000,    1,    2],
       [   3,    4,    5],
       [   6,    7,    8],
       [   9,   10,   11]])

In [36]:
fourth = np.arange(16)

In [37]:
fourth.reshape(5,5)

ValueError: cannot reshape array of size 16 into shape (5,5)

In [38]:
fourth.resize(2,8)

In [39]:
fourth

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [40]:
fourth.reshape(2,8)

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [41]:
fourth = first.astype(float)

In [42]:
fourth

array([1000.,    1.,    2.,    3.,    4.,    5.,    6.,    7.,    8.,
          9.,   10.,   11.])

In [46]:
np.zeros((10,10), dtype = np.int8)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int8)

In [45]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
np.full((5,5), 10)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])