In [20]:
import numpy as np

In [21]:
a = np.ones(3, dtype = np.int32)

In [22]:
from numpy import pi

In [23]:
b = np.linspace(0, 2*pi, 3)

In [24]:
a.dtype

dtype('int32')

In [25]:
c = a + b

In [26]:
c

array([1.        , 4.14159265, 7.28318531])

In [27]:
c * 1j

array([0.+1.j        , 0.+4.14159265j, 0.+7.28318531j])

In [29]:
d = np.exp(c)

In [30]:
d

array([   2.71828183,   62.90292428, 1455.6172365 ])

In [31]:
d = np.exp(c * 1j)

In [32]:
d

array([ 0.54030231+0.84147098j, -0.54030231-0.84147098j,
        0.54030231+0.84147098j])

In [35]:
a = np.random.random((2,3))

In [36]:
a

array([[0.61282987, 0.65976325, 0.77536367],
       [0.903237  , 0.02980152, 0.1273471 ]])

In [37]:
np.r_[1:4,0,4]

array([1, 2, 3, 0, 4])

In [63]:
np.c_[1:4]

array([[1],
       [2],
       [3]])

In [65]:
a = np.arange(12)

In [66]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [67]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [68]:
np.sin(np.arange(20))

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721])