In [1]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_regression

In [2]:
bias = 100
X, y = make_regression(n_features=4, bias=bias, noise=10, random_state=42)

In [3]:
class CustomCloseLinearReg:
    
    def fit(self, X, y):
        X = np.hstack([np.ones([X.shape[0], 1]), X])
        y = y.reshape(-1,1)
        
        first = np.linalg.inv(np.dot(X.T, X))
        second = np.dot(X.T, y)
        
        self.theta_ = np.dot(first, second)
        
    def predict(self, X):
        X = np.hstack([np.ones([X.shape[0], 1]), X])
        return np.dot(X, self.theta_)
        

In [4]:
model = CustomCloseLinearReg()

In [5]:
model.fit(X,y)

In [6]:
model.predict(X[:10])

array([[ 94.85255944],
       [ 50.34423332],
       [-30.07314717],
       [107.3453379 ],
       [-34.40987675],
       [143.55941103],
       [ 98.29972569],
       [ 67.75313807],
       [-58.48364998],
       [128.84465   ]])

In [9]:
from sklearn.datasets import load_boston

In [15]:
X,y = load_boston(return_X_y=True)

In [21]:
X.shape, y.shape

((506, 13), (506,))

In [16]:
model2 = CustomCloseLinearReg()

In [17]:
model2.fit(X,y)

In [29]:
model2.predict(X[:10])

array([[30.00384338],
       [25.02556238],
       [30.56759672],
       [28.60703649],
       [27.94352423],
       [25.25628446],
       [23.00180827],
       [19.53598843],
       [11.52363685],
       [18.92026211]])

In [24]:
from sklearn.linear_model import LinearRegression

In [25]:
m2 = LinearRegression()

In [26]:
m2.fit(X,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [28]:
m2.predict(X[:10])

array([30.00384338, 25.02556238, 30.56759672, 28.60703649, 27.94352423,
       25.25628446, 23.00180827, 19.53598843, 11.52363685, 18.92026211])